# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 50
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /
    registries:
      - maven-central
    open-pull-requests-limit: 50
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /test-project
    open-pull-requests-limit: 50
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /test-project-groovy
    open-pull-requests-limit: 50
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /test-project-kotlin
    open-pull-requests-limit: 50
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /test-project-kotlin-pre-1-7
    open-pull-requests-limit: 50
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /test-project-mixed
    open-pull-requests-limit: 50
    schedule:
      interval: monthly